@server = http://localhost:3000

# 게시글 조회
GET {{server}}/blog

### 게시글 생성
POST {{server}}/blog
Content-Type: application/json

{
  "title": "테스트 3",
  "content": "테스트 본문",
  "name": "동명이인"
}

### 특정 게시글 조회
GET {{server}}/blog/2

### 게시글 삭제
DELETE {{server}}/blog/2

### 게시글 수정
PUT {{server}}/blog/2
Content-Type: application/json

{
  "title": "수정 테스트 2",
  "content": "수정 테스트 본문 2",
  "name": "jreome.kim"
}